### ISSUE TITLE
Can you provide starting .uassets for UE 5.0 ?

### ISSUE THREAD

**Issue by sayandafadar** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#1]
Can you please provide starting .uassets from chapter 4 for UE 5.0 as it's not possible to downgrade .uassets if they are built using a higher UE version? 

Reason: UE 5.0 works on my machine fine but the newer versions doesn't work properly and I think this might be a problem for some people.

**Comment by marcosecchi** [comment]
Hello sayandafadar,
 unfortunately, it's not so easy to downgrade the assets to v. 5.0 from v5.1 project.
That said, those assets come from Kay Lousberg and are free for you to download here:
* Dungeon Pack: https://kaylousberg.itch.io/kaykit-dungeon
* Skeleton Pack: https://kaylousberg.itch.io/kaykit-skeletons
* Animation Pack: https://kaylousberg.itch.io/kaykit-animations

Hope this helps!

**Comment by sayandafadar** [comment]
Ok Thanks
