### ISSUE TITLE
Graph Printer plugin needed for Chapter 6

### ISSUE THREAD

**Issue by GaeaKat** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#2]
Chapter 6's download needs the Graph Printer plugin installed, something neither the book nor the github mentions

**Comment by GaeaKat** [comment]
May I ask how is this completed? The download still uses the plugin unmentioned.

**Comment by marcosecchi** [comment]
Hello @GaeaKat, I have added a comment in the dedicated [Errata page](https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/blob/main/errata.md).

**Comment by GaeaKat** [comment]
I see that now, thankyou! :), the trouble was it couldn’t be ignored, it errors fatally until installed or removed from the uproject!

**Comment by marcosecchi** [comment]
@GaeaKat as a quick solution, you can open the _.uproject_ file with a text editor and simply disable it.
