### ISSUE TITLE
Chapter 9 in UE5.3: Consume Input checkbox doesn't exist

### ISSUE THREAD

**Issue by yllamana** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#3]
Right at the bottom of page 199, the book refers to a "Consume Input" checkbox. In Unreal Engine 5.3, this checkbox does not seem to exist (though, confusingly, it still appears in the screenshot in the official documentation).

I noticed that the step to add the "Pressed" trigger, as you do on page 90 with the Interact input action, is also missing, though it looks like it might be reflected in the screenshot of the completed weapon action. So if you are, like me, on UE 5.3 and wondering why the book isn't mentioning the character attacking infinitely fast and messing up the montage, you probably need to add the Pressed trigger. 🙂

**Comment by marcosecchi** [comment]
Hello @yllamana, thanks for the heads-up!
I have made a comment on the dedicated page for utilizing UE 5.2+ version: https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/blob/main/ue-5-2.md
