### ISSUE TITLE
Chapter 6 - Replicating Properties Over the Network

### ISSUE THREAD

**Issue by LoganSmith2016** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#4]
![image](https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/assets/126133313/f14d3122-7def-4c18-b048-a38b15611f5b)
![image](https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/assets/126133313/aebca6a1-2c6d-4fc1-9937-4f42784d63fc)
![image](https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/assets/126133313/f2ec64f8-1e39-4f62-8965-10546ecf895d)

Function to return CharacterStats does not work. Keep getting error when compiling. How do I go about fixing this? Searched online and could not find anything helpful.

**Comment by marcosecchi** [comment]
Hello @LoganSmith2016 , from what I see in the Log, there is some kind of naming error (FUSCharacterStats vs FUS_CharacterStats): you most probably have refactored your code or there is a typo in it.
My advice is to try to download the available code on this repo and try to find what you did wrong in your code.

![chrome 240506 09-48-00](https://github.com/PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5/assets/752514/9c4eec41-d0ca-4a68-9a3b-b0367a1d9aa8)
