### ISSUE TITLE
Chapter 8 "Adding the navigation module" missing AIModule

### ISSUE THREAD

**Issue by dredgeho** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#6]
Page 166 says to add in NavigationSystem in the file: "UnrealShadows_LOTL.Build.cs" but doesn't say to add in AIModule to the line below:
PrivateDependencyModuleNames.AddRange(new string[] { }); 

Find where you added "NavigationSystem" shown below.

PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "EnhancedInput", "NavigationSystem"  });

And below that will be the line to change. Add in "AIModule" 
PrivateDependencyModuleNames.AddRange(new string[] {"AIModule"  });

The source would not compile without this.  The project would not open without this either.

**Comment by marcosecchi** [comment]
The aforementioned dependency is not needed.
