### ISSUE TITLE
Chapter 12: Book says Protected but the included code has Public

### ISSUE THREAD

**Issue by dredgeho** [PacktPublishing/Multiplayer-Game-Development-with-Unreal-Engine-5#8]
I'm having problems with Join Sessions so I'm looking in the code for why that's happening and I found this.

![image](https://github.com/user-attachments/assets/e500d55d-cd4f-464c-9944-b5942f527c11)

It says Protected in the book so in my code I put it in Protected. 
![image](https://github.com/user-attachments/assets/f83b7deb-80f3-45ef-ad25-bd6b873e692e)

Compare that to the included code:
![image](https://github.com/user-attachments/assets/c1f9882e-3c66-4f74-a7dc-701f1de61e17)

It's in Public... 

I don't know which place to put the code. Protected or Public?

**Comment by marcosecchi** [comment]
These are not really necessary for joining a connection, they are just getters for the main component. In the book, they are just used inside the class, so it doesn't matter if they are public or protected.

**Comment by marcosecchi** [comment]
Closing the issue.
